-- ==========================================
-- EXPANDED SEED DATA FOR DAILY CHALLENGE ARENA
-- 40 UNIQUE TECH-INTERVIEW-ORIENTED QUESTIONS PER SECTION
-- Topics: DSA, OOPS, OS, DBMS, Aptitude, AI, CN
-- Compatible with Supabase/PostgreSQL
-- ==========================================

INSERT INTO public.questions (topic, difficulty, question, options, correct_answer) VALUES
('DSA', 'Medium', 'Which data structure is most efficiently used to implement a Priority Queue?', '["Array", "Linked List", "Binary Heap", "Hash Table"]'::jsonb, 'Binary Heap'),
('DSA', 'Medium', 'What is the average-case time complexity of searching in a hash table with good hashing?', '["O(1)", "O(log N)", "O(N)", "O(N log N)"]'::jsonb, 'O(1)'),
('DSA', 'Medium', 'Which traversal of a Binary Search Tree produces values in sorted order?', '["Preorder", "Inorder", "Postorder", "Level Order"]'::jsonb, 'Inorder'),
('DSA', 'Hard', 'What is the worst-case time complexity of QuickSort?', '["O(log N)", "O(N log N)", "O(N^2)", "O(N^3)"]'::jsonb, 'O(N^2)'),
('DSA', 'Medium', 'Which algorithm is primarily used to find the shortest path in an unweighted graph?', '["DFS", "BFS", "Dijkstra", "Bellman-Ford"]'::jsonb, 'BFS'),
('DSA', 'Hard', 'Which algorithm can detect a negative-weight cycle reachable from the source?', '["Dijkstra", "Prim", "Bellman-Ford", "Kruskal"]'::jsonb, 'Bellman-Ford'),
('DSA', 'Medium', 'What is the time complexity of inserting an element into a balanced BST?', '["O(1)", "O(log N)", "O(N)", "O(N log N)"]'::jsonb, 'O(log N)'),
('DSA', 'Medium', 'Which data structure follows the LIFO principle?', '["Queue", "Stack", "Deque", "Heap"]'::jsonb, 'Stack'),
('DSA', 'Medium', 'Which data structure is commonly used for BFS?', '["Stack", "Queue", "Heap", "Hash Set"]'::jsonb, 'Queue'),
('DSA', 'Hard', 'Which algorithm is used to find strongly connected components in a directed graph?', '["KMP", "Kosaraju''s Algorithm", "Dijkstra", "Floyd-Warshall"]'::jsonb, 'Kosaraju''s Algorithm'),
('DSA', 'Medium', 'What is the time complexity of binary search on a sorted array?', '["O(1)", "O(log N)", "O(N)", "O(N log N)"]'::jsonb, 'O(log N)'),
('DSA', 'Hard', 'Which data structure supports range sum queries and point updates in O(log N)?', '["Stack", "Segment Tree", "Queue", "Linked List"]'::jsonb, 'Segment Tree'),
('DSA', 'Medium', 'Which algorithmic paradigm is primarily used for Longest Common Subsequence?', '["Greedy", "Divide and Conquer", "Dynamic Programming", "Backtracking"]'::jsonb, 'Dynamic Programming'),
('DSA', 'Medium', 'What is the main requirement for Dijkstra''s algorithm to work correctly?', '["Graph must be directed", "All edge weights must be non-negative", "Graph must be complete", "Graph must be acyclic"]'::jsonb, 'All edge weights must be non-negative'),
('DSA', 'Hard', 'Which algorithm finds a minimum spanning tree using edge sorting?', '["Dijkstra", "Kruskal", "DFS", "Bellman-Ford"]'::jsonb, 'Kruskal'),
('DSA', 'Medium', 'What is the amortized time complexity of push_back in a dynamic array?', '["O(1)", "O(log N)", "O(N)", "O(N^2)"]'::jsonb, 'O(1)'),
('DSA', 'Medium', 'Which data structure is best for checking duplicate elements efficiently?', '["Array", "Hash Set", "Stack", "Queue"]'::jsonb, 'Hash Set'),
('DSA', 'Hard', 'What is the worst-case lookup time in a balanced Red-Black Tree?', '["O(1)", "O(log N)", "O(N)", "O(N log N)"]'::jsonb, 'O(log N)'),
('DSA', 'Medium', 'Which sorting algorithm is stable by default in its standard implementation?', '["Heap Sort", "Merge Sort", "Selection Sort", "QuickSort"]'::jsonb, 'Merge Sort'),
('DSA', 'Medium', 'Which sorting algorithm has the best average-case complexity among these?', '["Bubble Sort", "Selection Sort", "Merge Sort", "Insertion Sort"]'::jsonb, 'Merge Sort'),
('DSA', 'Hard', 'What is the time complexity of Floyd-Warshall algorithm?', '["O(V+E)", "O(V^2)", "O(V^3)", "O(E log V)"]'::jsonb, 'O(V^3)'),
('DSA', 'Medium', 'What does topological sorting require?', '["Undirected graph", "Weighted graph", "Directed acyclic graph", "Complete graph"]'::jsonb, 'Directed acyclic graph'),
('DSA', 'Medium', 'Which technique is commonly used to detect a cycle in a linked list?', '["Binary Search", "Two Pointers", "Sliding Window", "Prefix Sum"]'::jsonb, 'Two Pointers'),
('DSA', 'Hard', 'What is the key idea behind KMP string matching?', '["Sorting the pattern", "Using an LPS array to avoid rechecking characters", "Using hashing only", "Trying all substrings"]'::jsonb, 'Using an LPS array to avoid rechecking characters'),
('DSA', 'Medium', 'Which data structure is used internally by recursive function calls?', '["Queue", "Stack", "Heap", "Trie"]'::jsonb, 'Stack'),
('DSA', 'Medium', 'What is the time complexity of building a heap from N elements?', '["O(N)", "O(N log N)", "O(log N)", "O(N^2)"]'::jsonb, 'O(N)'),
('DSA', 'Hard', 'Which algorithm is used for maximum flow problems?', '["Ford-Fulkerson", "Kruskal", "KMP", "Prim"]'::jsonb, 'Ford-Fulkerson'),
('DSA', 'Medium', 'A trie is most useful for which type of operation?', '["Range sum query", "Prefix searching", "Shortest path", "Median finding"]'::jsonb, 'Prefix searching'),
('DSA', 'Medium', 'What is the worst-case time complexity of lookup in a hash table?', '["O(1)", "O(log N)", "O(N)", "O(N log N)"]'::jsonb, 'O(N)'),
('DSA', 'Hard', 'Which technique is typically used to solve problems involving overlapping subproblems and optimal substructure?', '["Greedy", "Dynamic Programming", "DFS only", "Hashing only"]'::jsonb, 'Dynamic Programming'),
('DSA', 'Medium', 'What does a min-heap guarantee?', '["Root is largest", "Root is smallest", "All elements are sorted", "Left subtree is always smaller"]'::jsonb, 'Root is smallest'),
('DSA', 'Medium', 'Which graph representation is usually more space-efficient for sparse graphs?', '["Adjacency Matrix", "Adjacency List", "Incidence Matrix", "2D Prefix Array"]'::jsonb, 'Adjacency List'),
('DSA', 'Hard', 'Tarjan''s algorithm can be used to find which of the following?', '["Minimum spanning tree only", "Strongly connected components", "Binary search tree height", "Array inversions only"]'::jsonb, 'Strongly connected components'),
('DSA', 'Medium', 'What is the purpose of a monotonic stack?', '["Store random values", "Maintain elements in increasing or decreasing order", "Implement hashing", "Sort in O(1)"]'::jsonb, 'Maintain elements in increasing or decreasing order'),
('DSA', 'Medium', 'Which approach is commonly used for Two Sum in an unsorted array?', '["Nested loops only", "Hash Map", "Binary heap", "Trie"]'::jsonb, 'Hash Map'),
('DSA', 'Hard', 'What is the time complexity of finding the median of two sorted arrays using binary search partitioning?', '["O(N+M)", "O(log(min(N,M)))", "O(N log M)", "O(NM)"]'::jsonb, 'O(log(min(N,M)))'),
('DSA', 'Medium', 'Which traversal is typically used to compute shortest paths in an unweighted tree?', '["BFS", "Postorder", "Inorder", "Heap Sort"]'::jsonb, 'BFS'),
('DSA', 'Hard', 'What is the standard technique for answering many static range queries quickly?', '["Prefix Sum", "Recursion only", "Bubble Sort", "Linked List"]'::jsonb, 'Prefix Sum'),
('DSA', 'Medium', 'Which data structure is best suited for implementing an LRU Cache together with a hash map?', '["Singly Linked List", "Doubly Linked List", "Stack", "Trie"]'::jsonb, 'Doubly Linked List'),
('DSA', 'Hard', 'What is the purpose of coordinate compression?', '["Encrypt coordinates", "Reduce a large value range while preserving relative order", "Sort in O(1)", "Remove duplicates only"]'::jsonb, 'Reduce a large value range while preserving relative order'),
('OOPS', 'Medium', 'Which concept allows a subclass to provide a specific implementation of a superclass method?', '["Method Overloading", "Method Overriding", "Encapsulation", "Composition"]'::jsonb, 'Method Overriding'),
('OOPS', 'Medium', 'What does encapsulation primarily achieve?', '["Code reuse", "Data hiding and protection", "Multiple inheritance", "Memory allocation"]'::jsonb, 'Data hiding and protection'),
('OOPS', 'Medium', 'Which OOP feature allows one interface to represent many forms?', '["Encapsulation", "Polymorphism", "Aggregation", "Composition"]'::jsonb, 'Polymorphism'),
('OOPS', 'Hard', 'The Diamond Problem is mainly associated with which concept?', '["Garbage collection", "Multiple inheritance", "Exception handling", "Templates"]'::jsonb, 'Multiple inheritance'),
('OOPS', 'Medium', 'Which pattern restricts a class to exactly one instance?', '["Factory", "Observer", "Singleton", "Decorator"]'::jsonb, 'Singleton'),
('OOPS', 'Hard', 'Liskov Substitution Principle states that?', '["Classes should have one responsibility", "Derived classes must be substitutable for base classes", "Interfaces must be large", "Depend on concrete classes"]'::jsonb, 'Derived classes must be substitutable for base classes'),
('OOPS', 'Medium', 'Which keyword is commonly used in C++ to achieve runtime polymorphism?', '["static", "virtual", "const", "mutable"]'::jsonb, 'virtual'),
('OOPS', 'Medium', 'Method overloading is resolved at?', '["Runtime", "Compile time", "Link time", "Shutdown time"]'::jsonb, 'Compile time'),
('OOPS', 'Medium', 'Method overriding is mainly resolved at?', '["Compile time", "Runtime", "Preprocessing time", "Assembly time"]'::jsonb, 'Runtime'),
('OOPS', 'Hard', 'What is abstraction in OOP?', '["Showing implementation details", "Hiding unnecessary implementation details", "Duplicating code", "Allocating memory manually"]'::jsonb, 'Hiding unnecessary implementation details'),
('OOPS', 'Medium', 'What is a constructor primarily used for?', '["Destroy objects", "Initialize objects", "Sort objects", "Serialize objects"]'::jsonb, 'Initialize objects'),
('OOPS', 'Medium', 'Which special member function is called when an object is destroyed?', '["Constructor", "Copy constructor", "Destructor", "Friend function"]'::jsonb, 'Destructor'),
('OOPS', 'Hard', 'What is a pure virtual function in C++?', '["A virtual function with no implementation requirement in base class", "A static function", "A friend function", "A constructor"]'::jsonb, 'A virtual function with no implementation requirement in base class'),
('OOPS', 'Medium', 'A class containing at least one pure virtual function is called?', '["Static class", "Abstract class", "Final class", "Friend class"]'::jsonb, 'Abstract class'),
('OOPS', 'Medium', 'What does inheritance mainly promote?', '["Code reuse", "Memory leaks", "Disk I/O", "Deadlocks"]'::jsonb, 'Code reuse'),
('OOPS', 'Hard', 'What is object slicing in C++?', '["Deleting an object", "Losing derived-class information when copying to a base-class object by value", "Creating a virtual object", "Overloading an operator"]'::jsonb, 'Losing derived-class information when copying to a base-class object by value'),
('OOPS', 'Medium', 'Which relationship represents a strong ownership where part cannot exist independently?', '["Association", "Aggregation", "Composition", "Inheritance"]'::jsonb, 'Composition'),
('OOPS', 'Medium', 'Which relationship represents a weak has-a relationship?', '["Inheritance", "Composition", "Aggregation", "Polymorphism"]'::jsonb, 'Aggregation'),
('OOPS', 'Hard', 'Why should a polymorphic base class usually have a virtual destructor?', '["To speed compilation", "To correctly destroy derived objects through base pointers", "To prevent inheritance", "To create static objects"]'::jsonb, 'To correctly destroy derived objects through base pointers'),
('OOPS', 'Medium', 'Which access specifier makes members accessible only inside the class?', '["public", "protected", "private", "friend"]'::jsonb, 'private'),
('OOPS', 'Medium', 'Which access specifier allows access in derived classes but not from unrelated external code?', '["public", "private", "protected", "static"]'::jsonb, 'protected'),
('OOPS', 'Hard', 'What is the Open/Closed Principle?', '["Open for modification and closed for extension", "Open for extension and closed for modification", "Always use open source code", "Never modify classes"]'::jsonb, 'Open for extension and closed for modification'),
('OOPS', 'Medium', 'What is composition often preferred over inheritance for?', '["Code reuse with flexible object relationships", "Avoiding constructors", "Removing objects", "Sorting data"]'::jsonb, 'Code reuse with flexible object relationships'),
('OOPS', 'Hard', 'What does dependency inversion principle recommend?', '["Depend on abstractions, not concrete implementations", "Avoid interfaces", "Use global variables", "Avoid dependency injection"]'::jsonb, 'Depend on abstractions, not concrete implementations'),
('OOPS', 'Medium', 'Which pattern creates objects without exposing exact creation logic to the client?', '["Factory Pattern", "Observer Pattern", "Singleton Pattern", "Adapter Pattern"]'::jsonb, 'Factory Pattern'),
('OOPS', 'Medium', 'What is an interface primarily used for?', '["Store object state only", "Define a contract for behavior", "Allocate heap memory", "Replace constructors"]'::jsonb, 'Define a contract for behavior'),
('OOPS', 'Hard', 'What is shallow copy?', '["Copying nested objects completely", "Copying references or pointers without duplicating underlying resources", "Moving an object", "Deleting an object"]'::jsonb, 'Copying references or pointers without duplicating underlying resources'),
('OOPS', 'Hard', 'What is deep copy?', '["Copying references only", "Creating independent copies of owned resources", "Calling destructor twice", "Using only static data"]'::jsonb, 'Creating independent copies of owned resources'),
('OOPS', 'Medium', 'Which C++ keyword prevents a class from being inherited?', '["const", "final", "static", "volatile"]'::jsonb, 'final'),
('OOPS', 'Medium', 'What is function hiding in C++?', '["A derived function with the same name hides base overloads", "Deleting a function", "Making a function private", "Inlining a function"]'::jsonb, 'A derived function with the same name hides base overloads'),
('OOPS', 'Hard', 'What is the Rule of Three in C++ traditionally associated with?', '["Constructor, destructor, copy constructor/copy assignment management", "Three inheritance levels", "Three virtual functions", "Three interfaces"]'::jsonb, 'Constructor, destructor, copy constructor/copy assignment management'),
('OOPS', 'Medium', 'Which keyword gives a non-member function access to private members in C++?', '["virtual", "friend", "explicit", "override"]'::jsonb, 'friend'),
('OOPS', 'Medium', 'What does the override keyword help ensure?', '["Function is static", "Function correctly overrides a virtual base function", "Object is copied", "Memory is freed"]'::jsonb, 'Function correctly overrides a virtual base function'),
('OOPS', 'Hard', 'Which SOLID principle says clients should not be forced to depend on methods they do not use?', '["SRP", "OCP", "ISP", "DIP"]'::jsonb, 'ISP'),
('OOPS', 'Medium', 'What does SRP stand for?', '["Single Responsibility Principle", "Static Runtime Polymorphism", "Safe Resource Protocol", "Simple Reference Pattern"]'::jsonb, 'Single Responsibility Principle'),
('OOPS', 'Medium', 'Which OOP mechanism allows an object to contain another object as a member?', '["Composition", "Overloading", "Recursion", "Exception handling"]'::jsonb, 'Composition'),
('OOPS', 'Hard', 'What is dynamic binding?', '["Binding a method call at runtime based on actual object type", "Binding variables at compile time only", "Memory allocation", "Template expansion"]'::jsonb, 'Binding a method call at runtime based on actual object type'),
('OOPS', 'Medium', 'What is an object?', '["A blueprint for classes", "An instance of a class", "A memory leak", "A compiler"]'::jsonb, 'An instance of a class'),
('OOPS', 'Medium', 'What is a class?', '["An instance", "A blueprint for creating objects", "A thread", "A database table only"]'::jsonb, 'A blueprint for creating objects'),
('OOPS', 'Hard', 'What problem does RAII in C++ primarily solve?', '["Managing resources through object lifetime", "Sorting arrays", "Network routing", "SQL normalization"]'::jsonb, 'Managing resources through object lifetime'),
('OS', 'Medium', 'What is the primary purpose of a TLB?', '["Cache disk blocks", "Cache virtual-to-physical address translations", "Schedule CPU", "Handle interrupts"]'::jsonb, 'Cache virtual-to-physical address translations'),
('OS', 'Medium', 'Which scheduling algorithm may cause starvation?', '["Round Robin", "FCFS", "Priority Scheduling", "FIFO Paging"]'::jsonb, 'Priority Scheduling'),
('OS', 'Hard', 'Which condition is NOT required for deadlock?', '["Mutual Exclusion", "Hold and Wait", "Preemption", "Circular Wait"]'::jsonb, 'Preemption'),
('OS', 'Medium', 'What does starvation mean?', '["CPU is idle", "A process waits indefinitely for resources or CPU", "Memory is full", "Disk fails"]'::jsonb, 'A process waits indefinitely for resources or CPU'),
('OS', 'Medium', 'Which page replacement algorithm can suffer Belady''s anomaly?', '["LRU", "Optimal", "FIFO", "MRU"]'::jsonb, 'FIFO'),
('OS', 'Medium', 'What is the main purpose of a mutex?', '["Allow unlimited threads", "Provide mutual exclusion for one owner at a time", "Store files", "Schedule processes"]'::jsonb, 'Provide mutual exclusion for one owner at a time'),
('OS', 'Hard', 'What distinguishes a counting semaphore from a mutex?', '["Semaphore can permit multiple concurrent accesses", "Mutex permits multiple accesses", "No difference", "Semaphore is only for processes"]'::jsonb, 'Semaphore can permit multiple concurrent accesses'),
('OS', 'Medium', 'What is a context switch?', '["Switching disk sectors", "Saving and restoring CPU state between processes or threads", "Changing RAM size", "Changing page size"]'::jsonb, 'Saving and restoring CPU state between processes or threads'),
('OS', 'Medium', 'What is a process?', '["A program in execution", "A source file", "A CPU register", "A memory page"]'::jsonb, 'A program in execution'),
('OS', 'Medium', 'What is a thread?', '["An independent computer", "A lightweight execution unit within a process", "A disk block", "A compiler"]'::jsonb, 'A lightweight execution unit within a process'),
('OS', 'Hard', 'Which scheduling algorithm is optimal for minimizing average waiting time when burst times are known?', '["FCFS", "SJF", "Round Robin", "Priority"]'::jsonb, 'SJF'),
('OS', 'Medium', 'What is a system call?', '["A request from a program for an OS service", "A hardware interrupt only", "A database query", "A network packet"]'::jsonb, 'A request from a program for an OS service'),
('OS', 'Medium', 'Which memory technique divides memory into fixed-size blocks?', '["Segmentation", "Paging", "Swapping", "Compaction"]'::jsonb, 'Paging'),
('OS', 'Hard', 'What is thrashing?', '["CPU overheating", "Excessive paging causing very low useful CPU work", "Deadlock", "File corruption"]'::jsonb, 'Excessive paging causing very low useful CPU work'),
('OS', 'Medium', 'What is virtual memory?', '["Only physical RAM", "A technique giving processes an address space larger than physical memory", "CPU cache", "ROM"]'::jsonb, 'A technique giving processes an address space larger than physical memory'),
('OS', 'Medium', 'What is a race condition?', '["Processes execute alphabetically", "Program result depends on timing of concurrent operations", "Disk runs slowly", "CPU has one core"]'::jsonb, 'Program result depends on timing of concurrent operations'),
('OS', 'Hard', 'Which synchronization primitive is commonly used to avoid race conditions on a critical section?', '["Mutex", "Compiler", "Paging", "DMA"]'::jsonb, 'Mutex'),
('OS', 'Medium', 'What is a critical section?', '["Code that accesses shared resources", "Kernel boot code only", "Unused memory", "A disk partition"]'::jsonb, 'Code that accesses shared resources'),
('OS', 'Medium', 'What is FCFS scheduling?', '["First process with shortest burst", "First arrived process runs first", "Highest priority first", "Time quantum scheduling"]'::jsonb, 'First arrived process runs first'),
('OS', 'Medium', 'What is Round Robin scheduling based on?', '["Priority only", "Time quantum", "Shortest job", "Random selection"]'::jsonb, 'Time quantum'),
('OS', 'Hard', 'What is the convoy effect commonly associated with?', '["FCFS scheduling", "SJF scheduling", "LRU paging", "Demand paging"]'::jsonb, 'FCFS scheduling'),
('OS', 'Medium', 'What is deadlock?', '["Processes permanently waiting for each other", "CPU idle for one second", "A process exits", "Memory is cached"]'::jsonb, 'Processes permanently waiting for each other'),
('OS', 'Hard', 'Which strategy avoids deadlock by keeping the system in a safe state?', '["Banker''s Algorithm", "FIFO", "Round Robin", "LRU"]'::jsonb, 'Banker''s Algorithm'),
('OS', 'Medium', 'What is a page fault?', '["A syntax error", "Requested page is not currently in physical memory", "CPU crash", "Disk formatting"]'::jsonb, 'Requested page is not currently in physical memory'),
('OS', 'Medium', 'What is demand paging?', '["Loading all pages at startup", "Loading a page only when needed", "Removing all pages", "Using only ROM"]'::jsonb, 'Loading a page only when needed'),
('OS', 'Hard', 'Which page replacement algorithm is theoretical optimal but generally not implementable exactly?', '["FIFO", "Optimal", "LRU", "Clock"]'::jsonb, 'Optimal'),
('OS', 'Medium', 'What does the kernel primarily do?', '["Render web pages", "Manage hardware and system resources", "Compile all programs", "Store only user files"]'::jsonb, 'Manage hardware and system resources'),
('OS', 'Medium', 'What is an interrupt?', '["A request that causes CPU attention to shift to an event handler", "A deleted process", "A page table", "A file lock only"]'::jsonb, 'A request that causes CPU attention to shift to an event handler'),
('OS', 'Hard', 'What is DMA used for?', '["Direct memory transfer between devices and memory with limited CPU involvement", "CPU scheduling", "File compression", "Thread creation"]'::jsonb, 'Direct memory transfer between devices and memory with limited CPU involvement'),
('OS', 'Medium', 'What is fragmentation?', '["Unused memory space caused by allocation patterns", "CPU scheduling", "Database corruption", "Network delay"]'::jsonb, 'Unused memory space caused by allocation patterns'),
('OS', 'Medium', 'Internal fragmentation occurs when?', '["Allocated block contains unused space", "Free memory is scattered externally only", "Disk is full", "Page fault occurs"]'::jsonb, 'Allocated block contains unused space'),
('OS', 'Medium', 'External fragmentation occurs when?', '["Free memory is scattered into small non-contiguous blocks", "A page has unused bytes", "CPU is idle", "Cache is full"]'::jsonb, 'Free memory is scattered into small non-contiguous blocks'),
('OS', 'Hard', 'What is copy-on-write?', '["Copying all memory immediately", "Sharing data until a write requires a private copy", "Writing directly to disk only", "Disabling memory protection"]'::jsonb, 'Sharing data until a write requires a private copy'),
('OS', 'Medium', 'What is a zombie process?', '["A running process with high priority", "A terminated process whose status has not been collected by its parent", "A blocked thread", "A kernel thread"]'::jsonb, 'A terminated process whose status has not been collected by its parent'),
('OS', 'Medium', 'What is an orphan process?', '["A process whose parent has terminated", "A process with no memory", "A process in deadlock", "A process with no CPU"]'::jsonb, 'A process whose parent has terminated'),
('OS', 'Hard', 'Why can user-level threads be faster to switch than processes?', '["They never need memory", "They usually require less kernel involvement and state switching", "They use no CPU", "They cannot run concurrently"]'::jsonb, 'They usually require less kernel involvement and state switching'),
('OS', 'Medium', 'What is a file descriptor in Unix-like systems?', '["A CPU register", "An integer handle used to access an open file or resource", "A page number", "A thread ID only"]'::jsonb, 'An integer handle used to access an open file or resource'),
('OS', 'Medium', 'What is spooling?', '["Buffering jobs for a device such as a printer", "Deleting files", "CPU overclocking", "Memory compaction"]'::jsonb, 'Buffering jobs for a device such as a printer'),
('OS', 'Hard', 'What is the difference between user mode and kernel mode?', '["Kernel mode has privileged access to hardware and system resources", "User mode is always faster", "Kernel mode cannot access memory", "There is no difference"]'::jsonb, 'Kernel mode has privileged access to hardware and system resources'),
('OS', 'Medium', 'Which component translates virtual addresses to physical addresses?', '["MMU", "ALU", "NIC", "DMA Controller"]'::jsonb, 'MMU'),
('DBMS', 'Medium', 'Which normal form removes transitive dependency for non-prime attributes?', '["1NF", "2NF", "3NF", "4NF"]'::jsonb, '3NF'),
('DBMS', 'Hard', 'What does ACID Isolation guarantee?', '["Transactions are permanent", "Concurrent transactions do not improperly affect each other", "All transactions run sequentially", "Data is encrypted"]'::jsonb, 'Concurrent transactions do not improperly affect each other'),
('DBMS', 'Medium', 'Which SQL statement removes a table including its structure?', '["DELETE TABLE", "TRUNCATE TABLE", "DROP TABLE", "REMOVE TABLE"]'::jsonb, 'DROP TABLE'),
('DBMS', 'Hard', 'What is a primary advantage of a B+ tree index?', '["Data is only in internal nodes", "Leaf nodes support efficient sequential access", "It is not balanced", "It cannot index ranges"]'::jsonb, 'Leaf nodes support efficient sequential access'),
('DBMS', 'Medium', 'What is a foreign key?', '["Unique row identifier always", "Column referencing a key in another table", "Encrypted key", "Auto increment value"]'::jsonb, 'Column referencing a key in another table'),
('DBMS', 'Medium', 'Which SQL clause filters groups after GROUP BY?', '["WHERE", "HAVING", "ORDER BY", "DISTINCT"]'::jsonb, 'HAVING'),
('DBMS', 'Medium', 'Which JOIN returns only rows with matching values in both tables?', '["LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "FULL JOIN"]'::jsonb, 'INNER JOIN'),
('DBMS', 'Medium', 'What does a candidate key mean?', '["A minimal set of attributes that can uniquely identify a row", "Any non-unique column", "A foreign key only", "An index with duplicates"]'::jsonb, 'A minimal set of attributes that can uniquely identify a row'),
('DBMS', 'Hard', 'What is a deadlock in DBMS?', '["A query syntax error", "Transactions waiting indefinitely for each other''s locks", "A failed backup", "A missing index"]'::jsonb, 'Transactions waiting indefinitely for each other''s locks'),
('DBMS', 'Medium', 'What is an index primarily used for?', '["Increase table size only", "Speed up data retrieval", "Guarantee normalization", "Encrypt rows"]'::jsonb, 'Speed up data retrieval'),
('DBMS', 'Hard', 'Why can too many indexes hurt performance?', '["Indexes prevent SELECT", "They add overhead to INSERT, UPDATE and DELETE", "Indexes remove constraints", "They disable joins"]'::jsonb, 'They add overhead to INSERT, UPDATE and DELETE'),
('DBMS', 'Medium', 'What does COMMIT do?', '["Undoes changes", "Permanently saves current transaction changes", "Locks all tables forever", "Drops a database"]'::jsonb, 'Permanently saves current transaction changes'),
('DBMS', 'Medium', 'What does ROLLBACK do?', '["Permanently saves changes", "Reverses uncommitted transaction changes", "Creates an index", "Normalizes a table"]'::jsonb, 'Reverses uncommitted transaction changes'),
('DBMS', 'Hard', 'Which isolation issue occurs when one transaction reads uncommitted data written by another?', '["Dirty Read", "Phantom Read", "Deadlock", "Lost Update only"]'::jsonb, 'Dirty Read'),
('DBMS', 'Medium', 'What is a dirty read?', '["Reading uncommitted data", "Reading duplicate rows", "Reading only indexes", "Reading encrypted data"]'::jsonb, 'Reading uncommitted data'),
('DBMS', 'Hard', 'What is a phantom read?', '["Same row changes between reads", "New or removed rows appear in a repeated range query", "Reading uncommitted data", "A failed transaction"]'::jsonb, 'New or removed rows appear in a repeated range query'),
('DBMS', 'Medium', 'What is normalization primarily intended to reduce?', '["CPU speed", "Data redundancy and anomalies", "Network latency", "File size only"]'::jsonb, 'Data redundancy and anomalies'),
('DBMS', 'Medium', 'Which normal form requires atomic values?', '["1NF", "2NF", "3NF", "BCNF"]'::jsonb, '1NF'),
('DBMS', 'Medium', 'Which normal form removes partial dependency on part of a composite key?', '["1NF", "2NF", "3NF", "5NF"]'::jsonb, '2NF'),
('DBMS', 'Hard', 'BCNF is stricter than which normal form?', '["1NF", "2NF", "3NF", "4NF"]'::jsonb, '3NF'),
('DBMS', 'Medium', 'What is a composite key?', '["A key made from multiple attributes", "An encrypted key", "A duplicated key", "A foreign key"]'::jsonb, 'A key made from multiple attributes'),
('DBMS', 'Medium', 'What does NULL generally represent in SQL?', '["Zero", "Empty string always", "Unknown or missing value", "False"]'::jsonb, 'Unknown or missing value'),
('DBMS', 'Hard', 'Why is `= NULL` generally incorrect for testing NULL in SQL?', '["NULL is not a value comparable with ordinary equality; use IS NULL", "It causes syntax error always", "NULL equals zero", "It deletes rows"]'::jsonb, 'NULL is not a value comparable with ordinary equality; use IS NULL'),
('DBMS', 'Medium', 'Which clause sorts query results?', '["GROUP BY", "ORDER BY", "HAVING", "WHERE"]'::jsonb, 'ORDER BY'),
('DBMS', 'Medium', 'What is a view?', '["A physical duplicate table always", "A virtual table based on a query", "A transaction log", "An index type"]'::jsonb, 'A virtual table based on a query'),
('DBMS', 'Hard', 'What is denormalization?', '["Removing all keys", "Intentionally adding redundancy to improve read performance", "Deleting duplicate databases", "Encrypting tables"]'::jsonb, 'Intentionally adding redundancy to improve read performance'),
('DBMS', 'Medium', 'What is a transaction?', '["A logical unit of database work", "A database server", "An index", "A schema"]'::jsonb, 'A logical unit of database work'),
('DBMS', 'Medium', 'Which command removes all rows quickly while generally preserving the table structure?', '["DROP", "TRUNCATE", "ALTER", "CREATE"]'::jsonb, 'TRUNCATE'),
('DBMS', 'Hard', 'What is write-ahead logging?', '["Writing log records before modified data pages are written to durable storage", "Writing queries after execution only", "Deleting logs before commit", "Indexing logs"]'::jsonb, 'Writing log records before modified data pages are written to durable storage'),
('DBMS', 'Medium', 'What is referential integrity?', '["Ensuring valid relationships between related tables", "Ensuring all columns are integers", "Making queries faster", "Encrypting foreign keys"]'::jsonb, 'Ensuring valid relationships between related tables'),
('DBMS', 'Medium', 'What is a clustered index conceptually associated with?', '["Physical ordering or organization of table data by the index key", "Only unique constraints", "Hashing passwords", "Views"]'::jsonb, 'Physical ordering or organization of table data by the index key'),
('DBMS', 'Hard', 'What is the main benefit of database replication?', '["Always reduces schema size", "Improves availability and can improve read scalability", "Removes need for backups", "Eliminates consistency concerns"]'::jsonb, 'Improves availability and can improve read scalability'),
('DBMS', 'Medium', 'What does COUNT(*) count?', '["Only non-NULL values in one chosen column", "Rows returned by the query", "Only distinct values", "Only numeric values"]'::jsonb, 'Rows returned by the query'),
('DBMS', 'Medium', 'What does DISTINCT do?', '["Sorts rows", "Removes duplicate result values or rows", "Deletes duplicates from the table", "Creates an index"]'::jsonb, 'Removes duplicate result values or rows'),
('DBMS', 'Hard', 'What is a correlated subquery?', '["A subquery independent of outer query", "A subquery that references the outer query", "A query with no WHERE clause", "A stored procedure"]'::jsonb, 'A subquery that references the outer query'),
('DBMS', 'Medium', 'Which constraint prevents duplicate values?', '["CHECK", "UNIQUE", "DEFAULT", "FOREIGN KEY only"]'::jsonb, 'UNIQUE'),
('DBMS', 'Medium', 'What is a CHECK constraint used for?', '["Validate values against a condition", "Sort a table", "Create backups", "Join tables"]'::jsonb, 'Validate values against a condition'),
('DBMS', 'Hard', 'What is query optimization?', '["Changing table names", "Choosing an efficient execution plan for a query", "Deleting indexes always", "Running every query sequentially"]'::jsonb, 'Choosing an efficient execution plan for a query'),
('DBMS', 'Medium', 'Which JOIN keeps all rows from the left table and matching rows from the right?', '["INNER JOIN", "LEFT JOIN", "CROSS JOIN", "SELF JOIN"]'::jsonb, 'LEFT JOIN'),
('DBMS', 'Hard', 'What is a materialized view?', '["A view whose query result is physically stored and can be refreshed", "A view that cannot be queried", "A temporary SQL alias only", "A foreign key"]'::jsonb, 'A view whose query result is physically stored and can be refreshed'),
('Aptitude', 'Medium', 'A train 150m long runs at 60 km/h. How many seconds does it take to cross a 300m bridge?', '["20", "27", "18", "25"]'::jsonb, '27'),
('Aptitude', 'Medium', 'If the cost price of 20 articles equals the selling price of 15 articles, what is the profit percentage?', '["25%", "33.33%", "20%", "30%"]'::jsonb, '33.33%'),
('Aptitude', 'Hard', 'A can do a job in 15 days and B in 20 days. They work together for 4 days, then A leaves. How many more days does B need?', '["10 days", "10.66 days", "8 days", "12 days"]'::jsonb, '10.66 days'),
('Aptitude', 'Medium', 'The sum of ages of 5 children born 3 years apart is 50. What is the youngest age?', '["4", "8", "10", "2"]'::jsonb, '4'),
('Aptitude', 'Hard', 'In how many ways can the letters of OPTICAL be arranged so that all vowels are together?', '["120", "720", "4320", "2160"]'::jsonb, '720'),
('Aptitude', 'Medium', 'What is the simple interest on Rs. 5000 at 10% per annum for 2 years?', '["500", "1000", "1500", "2000"]'::jsonb, '1000'),
('Aptitude', 'Medium', 'A number increased by 20% becomes 120. What was the original number?', '["90", "100", "110", "96"]'::jsonb, '100'),
('Aptitude', 'Medium', 'A shop gives 10% discount on a marked price of Rs. 2000. What is the selling price?', '["1600", "1700", "1800", "1900"]'::jsonb, '1800'),
('Aptitude', 'Medium', 'If 5 workers finish a job in 12 days, how many days will 10 workers take at the same rate?', '["3", "6", "12", "24"]'::jsonb, '6'),
('Aptitude', 'Hard', 'A boat''s downstream speed is 15 km/h and upstream speed is 9 km/h. What is the speed of the boat in still water?', '["3", "6", "9", "12"]'::jsonb, '12'),
('Aptitude', 'Medium', 'What is the average of 10, 20, 30, 40 and 50?', '["20", "25", "30", "35"]'::jsonb, '30'),
('Aptitude', 'Medium', 'If the ratio of two numbers is 3:5 and their sum is 64, what is the larger number?', '["24", "32", "40", "48"]'::jsonb, '40'),
('Aptitude', 'Medium', 'A sum doubles in 8 years at simple interest. What is the annual interest rate?', '["8%", "10%", "12.5%", "15%"]'::jsonb, '12.5%'),
('Aptitude', 'Hard', 'What is the compound interest on Rs. 1000 at 10% per annum for 2 years?', '["200", "210", "220", "100"]'::jsonb, '210'),
('Aptitude', 'Medium', 'A person walks at 5 km/h. How long to cover 2.5 km?', '["20 min", "30 min", "40 min", "50 min"]'::jsonb, '30 min'),
('Aptitude', 'Medium', 'If x:y = 4:7 and y:z = 14:15, what is x:z?', '["4:15", "8:15", "7:15", "14:15"]'::jsonb, '8:15'),
('Aptitude', 'Hard', 'A and B invest Rs. 5000 and Rs. 8000 for the same time. If profit is Rs. 3900, B''s share is?', '["1500", "2000", "2400", "3000"]'::jsonb, '2400'),
('Aptitude', 'Medium', 'What is 25% of 480?', '["100", "110", "120", "125"]'::jsonb, '120'),
('Aptitude', 'Medium', 'A 20% increase followed by a 20% decrease results in?', '["No change", "4% increase", "4% decrease", "8% decrease"]'::jsonb, '4% decrease'),
('Aptitude', 'Hard', 'Two numbers have HCF 6 and LCM 180. If one number is 30, the other is?', '["24", "30", "36", "60"]'::jsonb, '36'),
('Aptitude', 'Medium', 'What is the probability of getting an even number on a fair six-sided die?', '["1/6", "1/3", "1/2", "2/3"]'::jsonb, '1/2'),
('Aptitude', 'Medium', 'How many diagonals does a hexagon have?', '["6", "8", "9", "12"]'::jsonb, '9'),
('Aptitude', 'Hard', 'How many ways can 3 people be selected from 8 people?', '["24", "56", "64", "336"]'::jsonb, '56'),
('Aptitude', 'Medium', 'A clock gains 5 minutes every hour. How many minutes will it gain in 6 hours?', '["5", "10", "25", "30"]'::jsonb, '30'),
('Aptitude', 'Medium', 'If 12% of x is 48, x is?', '["300", "400", "480", "600"]'::jsonb, '400'),
('Aptitude', 'Hard', 'A mixture contains milk and water in ratio 5:1. If 12 liters of water is added to 36 liters mixture, new milk:water ratio is?', '["5:2", "5:3", "3:2", "2:1"]'::jsonb, '5:3'),
('Aptitude', 'Medium', 'A car travels 240 km in 4 hours. Its average speed is?', '["40", "50", "60", "80"]'::jsonb, '60'),
('Aptitude', 'Medium', 'What is the next number: 2, 6, 12, 20, 30, ?', '["36", "40", "42", "44"]'::jsonb, '42'),
('Aptitude', 'Medium', 'If 3 pens cost Rs. 45, what do 7 pens cost at same rate?', '["90", "95", "100", "105"]'::jsonb, '105'),
('Aptitude', 'Hard', 'A sum is divided among A, B, C in ratio 2:3:5. If C gets Rs. 500, total sum is?', '["800", "900", "1000", "1200"]'::jsonb, '1000'),
('Aptitude', 'Medium', 'What is the value of 2^10?', '["512", "1000", "1024", "2048"]'::jsonb, '1024'),
('Aptitude', 'Medium', 'If a rectangle has length 12 and width 5, its area is?', '["17", "34", "60", "120"]'::jsonb, '60'),
('Aptitude', 'Medium', 'A square has perimeter 40. Its area is?', '["25", "50", "100", "160"]'::jsonb, '100'),
('Aptitude', 'Hard', 'A man sells an item at 20% loss for Rs. 800. What is its cost price?', '["900", "960", "1000", "1200"]'::jsonb, '1000'),
('Aptitude', 'Medium', 'If 4 machines make 400 items in 5 hours, how many items do 8 machines make in 5 hours?', '["400", "600", "800", "1600"]'::jsonb, '800'),
('Aptitude', 'Medium', 'What is the median of 2, 5, 7, 9, 12?', '["5", "7", "9", "12"]'::jsonb, '7'),
('Aptitude', 'Hard', 'A person spends 70% of income. If savings are Rs. 9000, income is?', '["20000", "25000", "30000", "35000"]'::jsonb, '30000'),
('Aptitude', 'Medium', 'If today is Monday, what day will it be after 100 days?', '["Tuesday", "Wednesday", "Thursday", "Friday"]'::jsonb, 'Wednesday'),
('Aptitude', 'Medium', 'What is 15% of 200 plus 20% of 300?', '["60", "75", "90", "100"]'::jsonb, '90'),
('Aptitude', 'Hard', 'A train crosses a pole in 10 seconds and a 300m platform in 25 seconds. What is train length?', '["100m", "150m", "200m", "250m"]'::jsonb, '200m'),
('AI', 'Medium', 'Which algorithm calculates gradients of loss with respect to neural network weights?', '["K-Means", "SVM", "Backpropagation", "A* Search"]'::jsonb, 'Backpropagation'),
('AI', 'Hard', 'In reinforcement learning, what does the Bellman equation help express?', '["Learning rate", "Relationship between value and future rewards", "Activation output", "Classification boundary"]'::jsonb, 'Relationship between value and future rewards'),
('AI', 'Medium', 'What is a primary use of CNNs?', '["Sorting arrays", "Image processing and pattern recognition", "Database indexing", "CPU scheduling"]'::jsonb, 'Image processing and pattern recognition'),
('AI', 'Hard', 'What happens in vanishing gradients?', '["Gradients become too small for early layers to learn effectively", "Model instantly overfits", "Outputs become infinite", "Dataset disappears"]'::jsonb, 'Gradients become too small for early layers to learn effectively'),
('AI', 'Medium', 'Which is an example of unsupervised learning?', '["Linear Regression", "Decision Tree", "K-Means Clustering", "Random Forest"]'::jsonb, 'K-Means Clustering'),
('AI', 'Medium', 'What is supervised learning trained with?', '["Only unlabeled data", "Labeled input-output examples", "No data", "Random policies only"]'::jsonb, 'Labeled input-output examples'),
('AI', 'Medium', 'What is overfitting?', '["Model performs well on training data but poorly on unseen data", "Model cannot learn training data", "Dataset is too small only", "Loss is always zero"]'::jsonb, 'Model performs well on training data but poorly on unseen data'),
('AI', 'Medium', 'What is regularization mainly used for?', '["Increase overfitting", "Reduce overfitting", "Remove labels", "Increase image size"]'::jsonb, 'Reduce overfitting'),
('AI', 'Hard', 'What is dropout?', '["Randomly disabling some units during training", "Deleting training data", "Stopping optimization permanently", "Changing labels"]'::jsonb, 'Randomly disabling some units during training'),
('AI', 'Medium', 'Which activation is commonly used to introduce non-linearity?', '["ReLU", "SQL", "BFS", "Hashing"]'::jsonb, 'ReLU'),
('AI', 'Hard', 'What is the exploding gradient problem?', '["Gradients grow extremely large during training", "Gradients become exactly zero only", "Dataset duplicates rows", "Model has no parameters"]'::jsonb, 'Gradients grow extremely large during training'),
('AI', 'Medium', 'What does gradient descent aim to minimize?', '["Number of features", "Loss function", "Dataset size", "GPU memory"]'::jsonb, 'Loss function'),
('AI', 'Medium', 'What is an epoch?', '["One complete pass through the training dataset", "One model parameter", "One hidden layer", "One feature"]'::jsonb, 'One complete pass through the training dataset'),
('AI', 'Hard', 'What is the purpose of a learning rate?', '["Controls optimization step size", "Counts classes", "Sets batch size only", "Defines dataset labels"]'::jsonb, 'Controls optimization step size'),
('AI', 'Medium', 'What is a confusion matrix used for?', '["Evaluate classification results", "Sort data", "Compress images", "Store gradients"]'::jsonb, 'Evaluate classification results'),
('AI', 'Medium', 'Precision is most concerned with?', '["Correct positive predictions among predicted positives", "Correct negatives only", "All samples equally", "Training speed"]'::jsonb, 'Correct positive predictions among predicted positives'),
('AI', 'Medium', 'Recall is most concerned with?', '["Correctly identifying actual positives", "Correctly identifying predicted negatives only", "Model size", "Learning rate"]'::jsonb, 'Correctly identifying actual positives'),
('AI', 'Hard', 'What does the F1 score combine?', '["Precision and recall", "Accuracy and loss", "Learning rate and epochs", "Bias and variance only"]'::jsonb, 'Precision and recall'),
('AI', 'Medium', 'What is feature engineering?', '["Creating or transforming useful input features", "Deleting all features", "Changing model hardware", "Encrypting labels"]'::jsonb, 'Creating or transforming useful input features'),
('AI', 'Hard', 'What is the bias-variance tradeoff about?', '["Balancing underfitting and overfitting tendencies", "Balancing CPU and RAM", "Balancing labels and features", "Balancing train and test file names"]'::jsonb, 'Balancing underfitting and overfitting tendencies'),
('AI', 'Medium', 'What is a validation set used for?', '["Tune and evaluate model choices during development", "Final deployment only", "Replace training data", "Store weights"]'::jsonb, 'Tune and evaluate model choices during development'),
('AI', 'Medium', 'What is transfer learning?', '["Using knowledge from a pretrained model for a new task", "Moving data between tables", "Changing programming languages", "Copying labels"]'::jsonb, 'Using knowledge from a pretrained model for a new task'),
('AI', 'Hard', 'What does attention in modern neural networks primarily help with?', '["Focusing computation on relevant parts of the input", "Sorting tensors only", "Reducing all parameters to zero", "Removing embeddings"]'::jsonb, 'Focusing computation on relevant parts of the input'),
('AI', 'Medium', 'What is an embedding?', '["A dense numerical representation of an item", "A SQL constraint", "A CPU instruction", "A sorting algorithm"]'::jsonb, 'A dense numerical representation of an item'),
('AI', 'Medium', 'What is a generative model designed to do?', '["Generate new data samples", "Only classify fixed labels", "Only sort data", "Only store databases"]'::jsonb, 'Generate new data samples'),
('AI', 'Hard', 'What is reinforcement learning based on?', '["Learning through rewards and feedback from interactions", "Only labeled examples", "Only clustering", "SQL joins"]'::jsonb, 'Learning through rewards and feedback from interactions'),
('AI', 'Medium', 'What is an agent in reinforcement learning?', '["Entity that takes actions in an environment", "A database index", "A compiler", "A dataset row"]'::jsonb, 'Entity that takes actions in an environment'),
('AI', 'Medium', 'What is an environment in reinforcement learning?', '["The system with which the agent interacts", "A neural network layer only", "A file format", "A database schema"]'::jsonb, 'The system with which the agent interacts'),
('AI', 'Hard', 'What does Q-learning estimate?', '["Action-value function", "Only learning rate", "Number of clusters", "Gradient norm only"]'::jsonb, 'Action-value function'),
('AI', 'Medium', 'Which technique is commonly used to reduce dimensionality?', '["PCA", "FCFS", "Kruskal", "Normalization only"]'::jsonb, 'PCA'),
('AI', 'Medium', 'What does PCA primarily maximize?', '["Variance captured by principal components", "Number of labels", "Database consistency", "Network bandwidth"]'::jsonb, 'Variance captured by principal components'),
('AI', 'Hard', 'What is cross-validation used for?', '["Estimate model generalization across different data splits", "Increase dataset labels", "Replace testing entirely", "Create gradients"]'::jsonb, 'Estimate model generalization across different data splits'),
('AI', 'Medium', 'What is batch size?', '["Number of samples processed before a parameter update", "Number of model layers", "Number of classes", "Number of epochs"]'::jsonb, 'Number of samples processed before a parameter update'),
('AI', 'Medium', 'What is a hyperparameter?', '["A setting chosen before or during training rather than learned directly from data", "A learned weight only", "A dataset row", "A prediction"]'::jsonb, 'A setting chosen before or during training rather than learned directly from data'),
('AI', 'Hard', 'Why is normalization often used for neural network inputs?', '["To place features on comparable scales and improve optimization", "To add labels", "To remove all variance", "To guarantee zero loss"]'::jsonb, 'To place features on comparable scales and improve optimization'),
('AI', 'Medium', 'What is tokenization in NLP?', '["Splitting text into units such as words or subwords", "Encrypting text", "Sorting characters only", "Removing all punctuation always"]'::jsonb, 'Splitting text into units such as words or subwords'),
('AI', 'Medium', 'Which model architecture is strongly associated with self-attention?', '["Transformer", "Heap", "B+ Tree", "Round Robin"]'::jsonb, 'Transformer'),
('AI', 'Hard', 'What is hallucination in generative AI?', '["Producing plausible but incorrect or unsupported content", "Model training faster", "Perfect factual recall", "Compressing embeddings"]'::jsonb, 'Producing plausible but incorrect or unsupported content'),
('AI', 'Medium', 'What is a loss function?', '["A function measuring prediction error", "A function that allocates RAM", "A network protocol", "A database key"]'::jsonb, 'A function measuring prediction error'),
('AI', 'Hard', 'What does gradient clipping help prevent?', '["Exploding gradients", "Overfitting only", "Data labeling", "Tokenization"]'::jsonb, 'Exploding gradients'),
('CN', 'Medium', 'Which OSI layer is responsible for routing packets?', '["Data Link", "Network", "Transport", "Session"]'::jsonb, 'Network'),
('CN', 'Medium', 'Which protocol is connection-oriented and reliable?', '["UDP", "TCP", "IP", "ARP"]'::jsonb, 'TCP'),
('CN', 'Medium', 'Which protocol is connectionless and has lower overhead?', '["TCP", "UDP", "HTTP", "FTP"]'::jsonb, 'UDP'),
('CN', 'Medium', 'What does DNS primarily do?', '["Maps domain names to IP addresses", "Encrypts packets", "Routes packets", "Assigns MAC addresses"]'::jsonb, 'Maps domain names to IP addresses'),
('CN', 'Medium', 'What does DHCP primarily provide?', '["Dynamic IP configuration", "Email delivery", "File transfer", "Web caching"]'::jsonb, 'Dynamic IP configuration'),
('CN', 'Hard', 'What is the TCP three-way handshake?', '["SYN, SYN-ACK, ACK", "ACK, FIN, SYN", "SYN, FIN, ACK", "ARP, DNS, ACK"]'::jsonb, 'SYN, SYN-ACK, ACK'),
('CN', 'Medium', 'Which protocol translates an IPv4 address to a MAC address on a local network?', '["DNS", "ARP", "HTTP", "ICMP"]'::jsonb, 'ARP'),
('CN', 'Medium', 'What is the purpose of a MAC address?', '["Identify a network interface at the data-link layer", "Identify a web page", "Encrypt a TCP connection", "Replace an IP address globally"]'::jsonb, 'Identify a network interface at the data-link layer'),
('CN', 'Medium', 'What does a router primarily do?', '["Connect and route traffic between networks", "Only connect devices within one LAN", "Store web pages", "Compile programs"]'::jsonb, 'Connect and route traffic between networks'),
('CN', 'Medium', 'What does a switch primarily use to forward Ethernet frames?', '["IP addresses only", "MAC address table", "Port 80", "DNS records"]'::jsonb, 'MAC address table'),
('CN', 'Hard', 'What is subnetting used for?', '["Divide an IP network into smaller networks", "Encrypt IP packets", "Increase CPU speed", "Replace DNS"]'::jsonb, 'Divide an IP network into smaller networks'),
('CN', 'Medium', 'Which HTTP method is typically used to retrieve a resource?', '["GET", "POST", "PUT", "DELETE"]'::jsonb, 'GET'),
('CN', 'Medium', 'Which HTTP status code means Not Found?', '["200", "301", "404", "500"]'::jsonb, '404'),
('CN', 'Medium', 'Which HTTP status code means Unauthorized?', '["201", "302", "401", "503"]'::jsonb, '401'),
('CN', 'Medium', 'What does HTTPS add to HTTP?', '["TLS encryption and authentication", "UDP only", "DNS routing", "File compression only"]'::jsonb, 'TLS encryption and authentication'),
('CN', 'Hard', 'What is the main purpose of TLS?', '["Provide encryption, integrity and authentication for communication", "Assign IP addresses", "Route packets", "Resolve DNS"]'::jsonb, 'Provide encryption, integrity and authentication for communication'),
('CN', 'Medium', 'What is NAT primarily used for?', '["Translate private and public network addresses", "Increase CPU clock", "Encrypt all files", "Replace TCP"]'::jsonb, 'Translate private and public network addresses'),
('CN', 'Medium', 'What is the default port for HTTP?', '["21", "22", "80", "443"]'::jsonb, '80'),
('CN', 'Medium', 'What is the default port for HTTPS?', '["25", "53", "110", "443"]'::jsonb, '443'),
('CN', 'Medium', 'Which protocol is commonly used for secure remote login?', '["Telnet", "SSH", "FTP", "SMTP"]'::jsonb, 'SSH'),
('CN', 'Medium', 'Which protocol is commonly used to send email between mail servers?', '["SMTP", "POP3", "IMAP", "FTP"]'::jsonb, 'SMTP'),
('CN', 'Medium', 'Which protocol allows clients to retrieve and manage email while keeping messages on the server?', '["SMTP", "IMAP", "ARP", "ICMP"]'::jsonb, 'IMAP'),
('CN', 'Hard', 'What is congestion control in TCP?', '["Mechanisms to prevent overwhelming the network", "Encryption of packets", "Assigning MAC addresses", "Caching DNS only"]'::jsonb, 'Mechanisms to prevent overwhelming the network'),
('CN', 'Medium', 'What is flow control?', '["Preventing a fast sender from overwhelming a slow receiver", "Routing around failures", "Encrypting traffic", "Resolving names"]'::jsonb, 'Preventing a fast sender from overwhelming a slow receiver'),
('CN', 'Hard', 'What does TCP''s sliding window help manage?', '["Flow control and efficient transmission", "DNS resolution", "MAC assignment", "HTTP caching only"]'::jsonb, 'Flow control and efficient transmission'),
('CN', 'Medium', 'What is packet switching?', '["Breaking data into packets that share network links", "Using only circuit paths", "Deleting packets", "Encrypting disks"]'::jsonb, 'Breaking data into packets that share network links'),
('CN', 'Medium', 'What is latency?', '["Time taken for data to travel from source to destination", "Maximum network capacity", "Packet size", "Number of routers"]'::jsonb, 'Time taken for data to travel from source to destination'),
('CN', 'Medium', 'What is bandwidth?', '["Maximum data transfer capacity of a link", "Travel time of a packet", "Packet loss percentage", "DNS lookup time"]'::jsonb, 'Maximum data transfer capacity of a link'),
('CN', 'Hard', 'What is the difference between a hub and a switch?', '["A hub broadcasts to all ports while a switch forwards based on MAC learning", "A switch cannot connect devices", "They are identical", "A hub routes between networks"]'::jsonb, 'A hub broadcasts to all ports while a switch forwards based on MAC learning'),
('CN', 'Medium', 'Which protocol is used for network diagnostic echo messages?', '["ICMP", "SMTP", "FTP", "TLS"]'::jsonb, 'ICMP'),
('CN', 'Medium', 'What does ping commonly use?', '["ICMP", "HTTP", "SMTP", "ARP only"]'::jsonb, 'ICMP'),
('CN', 'Hard', 'What is a firewall primarily used for?', '["Control and filter network traffic based on rules", "Resolve domain names", "Assign IP addresses", "Increase bandwidth"]'::jsonb, 'Control and filter network traffic based on rules'),
('CN', 'Medium', 'What is a proxy server?', '["An intermediary between client and another server", "A network cable", "A MAC address", "A routing protocol"]'::jsonb, 'An intermediary between client and another server'),
('CN', 'Medium', 'What is a CDN primarily used for?', '["Deliver content from distributed locations closer to users", "Assign private IPs", "Replace DNS completely", "Compile web apps"]'::jsonb, 'Deliver content from distributed locations closer to users'),
('CN', 'Hard', 'What is a load balancer used for?', '["Distribute traffic across multiple servers", "Increase one server''s CPU", "Encrypt only DNS", "Replace databases"]'::jsonb, 'Distribute traffic across multiple servers'),
('CN', 'Medium', 'What is IPv6 mainly designed to address?', '["IPv4 address exhaustion and other protocol improvements", "HTTP errors", "SQL transactions", "CPU scheduling"]'::jsonb, 'IPv4 address exhaustion and other protocol improvements'),
('CN', 'Medium', 'How many bits are in an IPv4 address?', '["16", "32", "64", "128"]'::jsonb, '32'),
('CN', 'Medium', 'How many bits are in an IPv6 address?', '["32", "64", "128", "256"]'::jsonb, '128'),
('CN', 'Hard', 'What is the purpose of a TCP sequence number?', '["Order bytes and detect missing data", "Resolve DNS", "Assign MAC addresses", "Set HTTP status"]'::jsonb, 'Order bytes and detect missing data'),
('CN', 'Medium', 'What does TTL stand for in IP networking?', '["Time To Live", "Total Transfer Limit", "Transport Tunnel Layer", "Traffic Type Length"]'::jsonb, 'Time To Live');
